import "./css/base.css";
import Menu from "../componentes/menu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Menu />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>LPR II 2025.</p>
        </footer>
      </body>
    </html>
  );
}
